"""add_email_confirmation_and_system_settings

Revision ID: cb580eb7c828
Revises: e7f8g9h0i1j2
Create Date: 2025-11-14 17:36:49.428662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb580eb7c828'
down_revision: Union[str, None] = 'e7f8g9h0i1j2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_user', sa.String(length=255), nullable=True),
    sa.Column('smtp_password', sa.Text(), nullable=True),
    sa.Column('smtp_from_email', sa.String(length=255), nullable=True),
    sa.Column('smtp_from_name', sa.String(length=255), nullable=True),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=False),
    sa.Column('require_email_confirmation', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.alter_column('household_memberships', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('inventory_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('inventory_items', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('locations', 'household_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('users', sa.Column('email_confirmation_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email_confirmation_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('email_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_users_email_confirmation_token'), 'users', ['email_confirmation_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_confirmation_token'), table_name='users')
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_column('users', 'email_confirmed_at')
    op.drop_column('users', 'email_confirmation_sent_at')
    op.drop_column('users', 'email_confirmation_token')
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.alter_column('locations', 'household_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory_items', 'image_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('inventory_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('1.0'),
               existing_nullable=False)
    op.alter_column('household_memberships', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'viewer'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
